apiVersion: v1
kind: Secret
metadata:
    name: {{ include "mychart.fullname" . }}-db-secret
type: Opaque
data:
  db-username: {{ .Values.database.username | b64enc | quote }}
  db-password: {{ .Values.database.password  | b64enc | quote }}
  db-root-password: {{ .Values.database.root_password  | b64enc | quote }}