--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ include "mychart.fullname" . }}-drupal-pvc
spec: 
  accessModes: 
    - {{ .Values.persistence.accessMode | quote }}
  resources: 
    requests: 
      storage: {{ .Values.persistence.size | quote }}
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ include "mychart.fullname" . }}-db-pvc
spec: 
  accessModes: 
    - {{ .Values.persistence.accessMode | quote }}
  resources: 
    requests: 
      storage: {{ .Values.persistence.size | quote }}
