apiVersion: v1
kind: Service
metadata: 
  name: {{ include "mychart.fullname" . }}-db-service
spec: 
  ports: 
    - name: "{{ .Values.database.name }}"
      port: {{ .Values.database.port }}
      protocol: TCP
  selector: 
    app: {{ include "mychart.fullname" . }}-db
---
apiVersion: v1
kind: Service
metadata: 
  name: {{ include "mychart.fullname" . }}-app-service
spec: 
  ports: 
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
  selector: 
    app: {{ include "mychart.fullname" . }}-drupal
  type: "{{ .Values.service.type }}"